<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-PCMJ85EN" failures="2" tests="3" name="inValidGet" time="0.621" errors="0" timestamp="2024-02-04T18:58:48 ICT">
  <testcase classname="com.restapi.testcase.Example2Test" name="TC01_statusCode" time="0.001"/>
  <testcase classname="com.restapi.testcase.Example2Test" name="TC02_MessageChecked" time="0.011">
    <failure type="java.lang.AssertionError" message="Message field check Failed! expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Message field check Failed! expected [false] but found [true]
at com.restapi.testcase.Example2Test.TC02_MessageChecked(Example2Test.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC02_MessageChecked -->
  <testcase classname="com.restapi.testcase.Example2Test" name="TC03_verifyOnMessageContent" time="0.017">
    <failure type="java.lang.AssertionError" message="Message is not matching! expected [User not found!] but found []">
      <![CDATA[java.lang.AssertionError: Message is not matching! expected [User not found!] but found []
at com.restapi.testcase.Example2Test.TC03_verifyOnMessageContent(Example2Test.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TC03_verifyOnMessageContent -->
</testsuite> <!-- inValidGet -->
